all:
  children:
    ansible:
      hosts:
        localhost:
          ansible_connection: local
          ansible_user: ubuntu
          hostname: AnsibleMaster
    prod:
      vars:
        env: production
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

      hosts:
        worker01:
          ansible_host: 172.31.95.37
          hostname: AnsibleWorker01
  
        worker02:
          ansible_host: 172.31.95.0
          hostname: AnsibleWorker02
